services:
  database:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    env_file:
      - .env

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    env_file:
      - .env

  scheduler:
    container_name: scheduler-service
    build: ../scheduler
    depends_on:
      - database
      - redis
    restart: always
    working_dir: /app
    command: >
      sh -c "alembic upgrade head && python db_init.py && python main.py"
    env_file:
      - .env
